# Generated by Django 6.0.7 on 2026-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_status', models.CharField(default='Pending', max_length=50)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_strengths', models.TextField(blank=True)),
                ('ai_weaknesses', models.TextField(blank=True)),
                ('ai_suggestions', models.TextField(blank=True)),
            ],
        ),
    ]
